changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
  categories:
    - title: "⚠️ Breaking changes"
      labels:
        - breaking-change
        - semver-major
    - title: "✨ New features"
      labels:
        - feature
        - enhancement
        - semver-minor
    - title: "🐛 Bug fixes"
      labels:
        - bug
        - bugfix
        - fix
    - title: "🔒 Security"
      labels:
        - security
    - title: "📚 Documentation"
      labels:
        - documentation
        - docs
    - title: "📦 Dependencies"
      labels:
        - dependencies
    - title: "Other changes"
      labels:
        - "*"
